### ISSUE TITLE
ts-node から tsx への移行

### ISSUE THREAD

**Issue by nissy-dev** [nissy-dev/blog#131]
tsx が --tsconfig オプションをリリースしたので、簡単に移行できそうかと思ったけどそうでもなかった...

```
> blog@0.1.0 build:static
> tsx --tsconfig tsconfig.script.json scripts/generateStaticFiles.tsx

/Users/nissy-dev/code/github.com/nissy-dev/blog/scripts/generateStaticFiles.tsx:66
  const markup = ReactDOM.renderToStaticMarkup(<OGPContent {...props} />);
                                               ^

ReferenceError: React is not defined
    at null.generateOgpImage (/Users/nissy-dev/code/github.com/nissy-dev/blog/scripts/generateStaticFiles.tsx:66:48)
    at null.<anonymous> (/Users/nissy-dev/code/github.com/nissy-dev/blog/scripts/generateStaticFiles.tsx:59:68)
    at Array.map (<anonymous>)
    at null.generateOgpImages (/Users/nissy-dev/code/github.com/nissy-dev/blog/scripts/generateStaticFiles.tsx:59:39)
    at async Promise.all (index 1)
    at null.main (/Users/nissy-dev/code/github.com/nissy-dev/blog/scripts/generateStaticFiles.tsx:82:3)
```

tsx は esbuild を使って ts ファイルを１つのファイルにバンドルして実行させる感じっぽい。
esbuild は polyfill に関して何も関与しないはずなので、確かに React v17 以降の react を import しなくなった世界では、
react に関して何か polyfill みたいなものを当てる必要がありそう...?

vite とか esbuild-loader とかがどうなっているのか、コードを読んだ方がよさそう

**Comment by nissy-dev** [comment]
ライブラリ作者は inject してくれって言っている
https://github.com/privatenumber/esbuild-loader/issues/184

esbuild-loader の example でも、webpack plugin で react を provide していた

https://github.com/privatenumber/esbuild-loader-examples/blob/52ca91b8cb2080de5fc63cc6e9371abfefe1f823/examples/react/webpack.config.js#L39

**Comment by nissy-dev** [comment]
inject しようと思ったけど、tsxの作りが inject を簡単に受け取れるようになっていない....
[esm-loader](https://github.com/esbuild-kit/esm-loader) とかから 修正していかないとキツそう

React を import or 普通に webpack 使って言われそうだから、一旦 ts-node のままでいいや
https://esbuild.github.io/content-types/#auto-import-for-jsx

**Comment by nissy-dev** [comment]
ブランチは残しておいた https://github.com/nissy-dev/blog/tree/try-tsx
